Nosto/search-js

- .github/workflows/publish.yml
> fix: remove duplicated workflow

- package.json
- src/currencies.ts
- src/currencies/priceDecorator.ts
- src/index.ts
- src/search.ts
- src/thumbnails.ts
- src/thumbnails/generateThumbnailUrl.ts
- src/thumbnails/shopifyThumbnailDecorator.ts
- src/thumbnails/thumbnailDecorator.ts
- src/thumbnails/types.ts
> Add module output in typedocs

- src/index.ts
- src/search.ts
- src/types.ts
- test/search.spec.ts
> Infer result type from hit decorators

- test/search/search.shouldRetry.spec.ts
Moving the test from search-templates.
Related to: https://nostosolutions.atlassian.net/browse/CFE-789
> chore: add extra test file

- src/currencies/priceDecorator.ts
- src/thumbnails/thumbnailDecorator.ts
> Improve docs

- src/search/types.ts
Makes usage of Options type more convenient when custom hit decorator typing is not needed
> Add default for type parameter

- src/thumbnails/shopifyThumbnailDecorator.ts
- test/thumbnails/shopifyThumbnailDecorator.spec.ts
> Support nosto sizes in Shopify thumbnail decorator

- .github/workflows/release.yml
> Bump action versions

- eslint.config.js
- package-lock.json
- package.json
- packages/core/index.ts
- packages/core/src/applyDecorators.ts
- packages/core/src/search.ts
- packages/core/src/searchWithRetries.ts
- packages/core/test/search.shouldRetry.spec.ts
- packages/core/test/search.spec.ts
- packages/core/vite.config.ts
- packages/currencies/index.ts
- packages/currencies/src/getCurrencyFormatting.ts
- packages/currencies/src/priceDecorator.ts
- packages/currencies/test/getCurrencyFormatting.spec.ts
- packages/currencies/test/priceDecorator.spec.ts
- packages/currencies/vite.config.ts
- packages/preact/test/hooks/usePersonalization.spec.ts
- packages/preact/vite.config.ts
- packages/thumbnails/index.ts
- packages/thumbnails/src/generateThumbnailUrl.ts
- packages/thumbnails/src/nostoThumbnailDecorator.ts
- packages/thumbnails/src/shopifyThumbnailDecorator.ts
- packages/thumbnails/src/thumbnailDecorator.ts
- packages/thumbnails/test/generateThumbnailUrl.spec.ts
- packages/thumbnails/test/shopifyThumbnailDecorator.spec.ts
- packages/thumbnails/test/thumbnailDecorator.spec.ts
- packages/thumbnails/vite.config.ts
Introduces two new eslint rules to automate and improve import handling.
https://www.npmjs.com/package/eslint-plugin-unused-imports
https://www.npmjs.com/package/eslint-plugin-simple-import-sort
> Introduce import lint rules

- packages/preact/src/actions/newSearch.ts
- packages/preact/src/actions/types.ts
- packages/preact/src/actions/updateSearch.ts
- packages/preact/src/api/types.ts
- packages/preact/src/config/base/baseConfig.ts
- packages/preact/src/config/configContext.tsx
- packages/preact/src/config/pages/serp/config.ts
- packages/preact/src/hooks/useActions.ts
- packages/preact/src/search/defaults.ts
- packages/preact/src/search/resultCaching.ts
- packages/preact/src/store.tsx
- packages/preact/test/actions/newSearch.spec.ts
- packages/utils/src/deepMerge.ts
- packages/utils/src/mergeArrays.ts
- packages/utils/src/performance.ts
- packages/utils/src/storage.ts
- packages/utils/src/unique.ts
- packages/utils/test/deepMerge.spec.ts
Moves useActions hook partially, implementing newSearch and updateSearch functions. The rest of the changes are basically dependencies.
> chore: move useActions

- package.json
- packages/core/core.ts
- packages/core/src/types.ts
- packages/currencies/currencies.ts
- packages/currencies/src/getCurrencyFormatting.ts
> Fix all typedoc warnings

- packages/preact/src/actions/replaceFilter.ts
- packages/preact/src/actions/toggleProductFilter.ts
- packages/preact/src/hooks/useActions.ts
- packages/preact/test/actions/replaceFilter.spec.ts
- packages/preact/test/actions/toggleProductFilter.spec.ts
- packages/preact/test/actions/updateSearch.spec.ts
Moves the updateFilter actions from library as-is.
The tests are all freshly written.
It's still the same ticket, I'm too lazy to add it every time. :)
> chore: move filter actions

- packages/preact/src/hooks/useSizeOptions.ts
- packages/preact/test/hooks/useSizeOptions.spec.ts
> Move useSizeOptions hook

- packages/preact/src/hooks/useFacets.ts
- packages/preact/src/hooks/useResponse.ts
- packages/preact/src/hooks/useSelectedFiltersCount.ts
- packages/preact/test/hooks/useFacets.spec.ts
- packages/preact/test/hooks/useResponse.spec.ts
- packages/preact/test/hooks/useSelectedFiltersCount.spec.ts
Moves a few more convenience hooks
> chore: move more convenience hooks

- packages/preact/src/hooks/useProductFilters/useProductFilters.tsx
- packages/preact/src/hooks/useProductFilters/useProductFiltersUtils.ts
- packages/preact/test/hooks/useProductFilters.spec.ts
Adds the hook, heavily refactored from the original form.
> chore: move useProductFilters hook

- packages/preact/src/actions/toggleProductFilter.ts
- packages/preact/src/hooks/useProductFilters/useProductFiltersUtils.ts
> chore: drop legacy

- packages/utils/src/parseNumber.ts
- packages/utils/test/isEqual.spec.ts
- packages/utils/test/isPlainObject.spec.ts
- packages/utils/test/parseNumber.spec.ts
- packages/utils/test/performance.spec.ts
- packages/utils/test/unique.spec.ts
Adds parseNumber util (to be used in the next PR) and a bunch of tests for it and other utilities
> chore: add parseNumber util and missing tests

- packages/preact/src/hooks/useRange.ts
- packages/preact/src/hooks/useRangeSelector.ts
- packages/preact/test/hooks/useRange.spec.ts
- packages/preact/test/hooks/useRangeSelector.spec.ts
- packages/preact/test/mocks/mocks.ts
- packages/utils/src/mergeArrays.ts
- packages/utils/src/types.ts
Moves useRange and useRangeSelector hooks.
> chore: move useRange hooks

- .github/workflows/release.yml
> chore: fix ci

- dev/preact/package-lock.json
- package-lock.json
- package.json
- packages/core/core.ts
- packages/core/src/addToCart.ts
- packages/core/src/shims.d.ts
- packages/core/test/addToCart.spec.ts
- packages/thumbnails/src/utils/shims.d.ts
Function to add a product to shopping cart and attribute the cart addition to Nosto Search
https://nostosolutions.atlassian.net/browse/CFE-689
> Add function for add to cart attribution

- packages/preact/src/hooks/usePagination/usePagination.ts
> fix: use big memo in usePagination

- packages/preact/test/components/InfiniteScroll/InfiniteScroll.spec.tsx
> chore: added tests for infinite scroll

- dev/preact/src/components/Header.tsx
- dev/preact/src/index.tsx
- dev/preact/src/pages/Autocomplete/Autocomplete.tsx
- dev/preact/src/pages/Autocomplete/Content.tsx
- dev/preact/src/pages/Autocomplete/Product.tsx
- dev/preact/src/pages/Autocomplete/Results.tsx
- packages/preact/preact.ts
- packages/preact/src/components/Autocomplete/AutocompleteElement.tsx
- packages/preact/src/components/Autocomplete/utils.ts
- packages/preact/test/components/AutocompleteElement.spec.tsx
Adds lower level autocomplete element component 
https://nostosolutions.atlassian.net/browse/CFE-925
> Chore: move autocomplete element component

- typedoc.json
Fix typedoc being not very smart.
> chore: fix typedoc

- README.md
- dev/preact/test/imports.spec.tsx
> docs: updated documentation

- packages/core/core.ts
- packages/core/src/search.ts
- packages/core/src/searchWithRetries.ts
- packages/core/src/types.ts
- packages/preact/src/actions/newSearch.ts
- packages/preact/src/actions/updateSearch.ts
- packages/preact/src/config/base/baseConfig.ts
> feat: rename generic Options to SearchOptions

- packages/utils/src/deepMerge.ts
> fix: remove type and logic overlap

- packages/utils/src/deepMerge.ts
- packages/utils/src/isEqual.ts
- packages/utils/src/isPlainObject.ts
- packages/utils/src/mergeArrays.ts
- packages/utils/src/parseNumber.ts
- packages/utils/src/performance.ts
- packages/utils/src/unique.ts
- packages/utils/utils.ts
> fix: added comments for utils

- packages/preact/src/actions/newSearch.ts
- packages/preact/src/api/types.ts
- packages/preact/src/components/SerpElement.tsx
- packages/preact/src/config/configContext.tsx
- packages/preact/src/config/pages/category/config.ts
- packages/preact/src/config/pages/serp/config.ts
- packages/preact/test/actions/newSearch.spec.ts
> fix: pageType to be compatible with search-templates

- packages/thumbnails/src/shopifyThumbnailDecorator.ts
- packages/thumbnails/test/shopifyThumbnailDecorator.spec.ts
- packages/thumbnails/test/thumbnailDecorator.spec.ts
https://nostosolutions.atlassian.net/browse/CFE-982
> feat: Fix shopify thumbnails

- packages/preact/src/hooks/useSizeOptions.ts
- packages/preact/test/hooks/useSizeOptions.spec.ts
> fix: string case included for useSizeOptions

- packages/utils/test/logger.spec.ts
> chore: add missing tests

- packages/utils/src/bindInput.ts
- packages/utils/test/bindInput.spec.ts
Move input binding logic from search-templates and nosto-autocomplete to search-js
https://nostosolutions.atlassian.net/browse/CFE-1009
> feat: input bindings for autocomplete

- packages/utils/utils.ts
Adds exports to utils.ts for bindInput and related exports which were added here: https://github.com/Nosto/search-js/pull/169
> feat: add bindInput exports

- .gitignore
- package-lock.json
- package.json
- vite.config.ts
https://nostosolutions.atlassian.net/browse/CFE-1024
> chore: add test coverage threshold

- packages/utils/src/storage.ts
> chore: drop info logging

- packages/core/src/resultCaching.ts
- packages/core/src/withCache.ts
- packages/core/test/searchWithCache.spec.ts
- packages/preact/test/actions/newSearch.spec.ts
Use provided search function in all cases
> fix: use provided function

- packages/core/test/search.withCache.spec.ts
- packages/preact/test/actions/newSearch.spec.ts
> chore: cleanup caching tests

- packages/preact/src/hooks/useActions.ts
- packages/preact/src/hooks/useDecoratedSearchResults.ts
- packages/preact/src/hooks/useFacet.ts
- packages/preact/src/hooks/useFacets.ts
- packages/preact/src/hooks/useLoadMore/useLoadMore.ts
- packages/preact/src/hooks/useNostoAppState.ts
- packages/preact/src/hooks/usePagination.ts
- packages/preact/src/hooks/usePersonalization.ts
- packages/preact/src/hooks/useProductFilters/useProductFilters.tsx
- packages/preact/src/hooks/useRange.ts
- packages/preact/src/hooks/useRangeSelector.ts
- packages/preact/src/hooks/useResponse.ts
- packages/preact/src/hooks/useSelectedFiltersCount.ts
- packages/preact/src/hooks/useSizeOptions.ts
- packages/preact/src/hooks/useSort/useSort.ts
> chore: fix imports in examples

- packages/core/src/applyDecorators.ts
- packages/core/src/resultCaching.ts
- packages/core/src/search.ts
- packages/core/src/types.ts
- packages/core/src/withCache.ts
- packages/core/src/withRetries.ts
- packages/core/test/search.withCache.spec.ts
> chore: simplify generics

- packages/core/src/withCache.ts
- packages/core/test/search.withCache.spec.ts
> fix: adjust response size in merge

- packages/utils/src/bindInput.ts
- packages/utils/test/bindInput.spec.ts
> Revert "fix: remove onSubmit triggering in onKeyDown"

- packages/core/src/resultCaching.ts
- packages/core/test/search.withCache.spec.ts
Use TTL of one minute for persistent cache
> fix: add missing cache ttl

- packages/preact/hooks.ts
- packages/preact/src/hooks/useFacet.ts
- packages/preact/test/hooks/useFacet.spec.ts
Allows to force the initial state of the useFacet hook.
Also adds tests with 100% statement, branch, function and line coverage for the hook. 🙂 
https://nostosolutions.atlassian.net/browse/CFE-1014
> feat: add options to useFacet hook

- packages/core/src/withCache.ts
- packages/core/test/search.withCache.spec.ts
> fix: use result size instead of hits.length

- packages/preact/src/hooks/useSwatches/aggregateSwatches.ts
- packages/preact/src/hooks/useSwatches/applySelectionStates.ts
- packages/preact/src/hooks/useSwatches/useSwatches.ts
- packages/preact/test/hooks/useSwatches.spec.ts
Skip empty options to be able to add multiple custom field keys that are not all used in all products
> feat: skip empty options

- packages/core/src/addToCart.ts
> chore: improve nostojs usage

- dev/preact/tsconfig.json
- package.json
- packages/preact/autocomplete/src/AutocompletePageProvider.tsx
- packages/preact/category/src/CategoryPageProvider.tsx
- packages/preact/common/src/store/components/StoreActionsListener.tsx
- packages/preact/events/events.ts
- packages/preact/events/src/eventBusDispatch.ts
- packages/preact/events/src/eventBusSubscribe.ts
- packages/preact/events/src/types.ts
- packages/preact/serp/src/SerpPageProvider.tsx
- tsconfig.json
- vite.config.ts
Adds an ability to call actions on a specific store using custom events (in a type-safe way).
> feat: add store actions event listeners

- dev/preact/src/contexts/InfiniteScrollContext.tsx
- dev/preact/src/pages/Autocomplete/components/AutocompleteHistory.tsx
- dev/preact/src/pages/Autocomplete/components/AutocompleteHistoryElement.tsx
- dev/preact/src/pages/Autocomplete/components/AutocompleteKeyword.tsx
- dev/preact/src/pages/Search/components/SearchQueryHandler.tsx
- dev/preact/src/style.css
- packages/preact/autocomplete/autocomplete.ts
- packages/preact/autocomplete/src/components/AutocompleteElement.tsx
- packages/preact/autocomplete/src/components/HistoryElement.tsx
- packages/preact/common/src/components/BaseElement.tsx
- packages/preact/inject/src/init/autocomplete/AutocompleteContext.tsx
- packages/preact/inject/src/init/autocomplete/bindAutocompleteInput.tsx
- packages/preact/inject/src/init/autocomplete/createElements.tsx
- packages/preact/inject/src/init/autocomplete/events/onFocus.tsx
- packages/preact/inject/src/init/autocomplete/events/onInput.tsx
- packages/preact/inject/src/init/autocomplete/events/onKeyDown.tsx
- packages/preact/inject/src/init/autocomplete/events/onSubmit.tsx
- packages/preact/inject/src/init/injectAutocomplete.tsx
Reintroduces history support (in inject mode), fixes keyboard navigation.
Autocomplete injection clean up part 2/3 (ish).
> fix: history and keyboard navigation

- packages/preact/inject/src/init.ts
> chore: deconstruct config

- packages/preact/inject/src/helpers/dom.ts
Remove unused exports and simplify existing ones
> chore: simplify dom utils

- packages/preact/common/src/store/components/StoreActionsListener.tsx
- packages/preact/hooks/src/useProductFilters/useProductFilters.tsx
Adjustment to make the events/* namespace for notifcations only
Actions should be passed via actions/*
> fix: make removeAllFilters event notification only

- packages/preact/common/src/store/storeExtensions.tsx
- packages/preact/hooks/test/hooks/useNostoAppState.spec.tsx
Fix store onChange logic by setting correct initial selector value state instead of undefined, which skips transitions to undefined
https://nostosolutions.atlassian.net/browse/CFE-1331
> fix: fix onChange logic

- packages/core/core.ts
> fix: use core prefix instead of ./

- .github/workflows/copilot-setup-steps.yml
> chore: further copilot setup improvements
